default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Mamakobe254!
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: karibu_system_development

test:
  <<: *default
  database: karibu_system_test

production:
  <<: *default
  database: karibu_system_development
  username: root
  password: Mamakobe254!
